package id.ac.poliban.mi.andre.ligainggris;

import java.util.ArrayList;
import java.util.List;

public class ClubData {
    static List<Club> getClubList(){
        List<Club> data = new ArrayList<>();
        {
            data.add(new Club("https://upload.wikimedia.org/wikipedia/id/thumb/c/cc/Chelsea_FC.svg/200px-Chelsea_FC.svg.png","Chelsea F.C.","Chelsea Football Club /ˈtʃɛlsiː/ adalah sebuah klub sepak bola Inggris yang bermarkas di Fulham, London. Chelsea didirikan pada tahun 1905 dan kini berkompetisi di Liga Utama Inggris.\nKesuksesan pertama Chelsea diraih saat meraih gelar juara liga pada tahun 1955. Beberapa gelar dari berbagai kompetisi juga berhasil diraih pada dekade 1960an, 1970an, 1990an, dan 2000an. Sepanjang sejarah penampilan dalam dunia sepak bola di Inggris dan Eropa, Chelsea telah meraih enam gelar juara Liga Utama Inggris, delapan Piala FA, lima Piala Liga, dua Liga Eropa UEFA, dua Piala Winners UEFA, satu Liga Champions UEFA, dan satu Piala Super UEFA.[3] Dalam dua dekade terakhir merupakan periode terbaik kesuksesan Chelsea dengan meraih lebih dari 30 gelar sejak tahun 1997, termasuk untuk pertama kali meraih gelar ganda, Liga Utama Inggris dan Piala FA pada tahun 2010 serta gelar juara Liga Champions UEFA pada tahun 2012 dan Liga Eropa UEFA pada 2013 dan 2019."));
            data.add(new Club("https://upload.wikimedia.org/wikipedia/id/thumb/5/53/Arsenal_FC.svg/180px-Arsenal_FC.svg.png", "Arsenal F.C.", "Arsenal Football Club (dikenal pula sebagai Arsenal atau The Gunners) adalah klub sepak bola profesional Inggris yang berbasis di daerah Holloway, London. didirikan pada 1886 dengan nama Dial Square. Klub ini bermain di Liga Utama Inggris yang termasuk salah satu klub tersukses di sepak bola Inggris, yang telah memenangkan 13 gelar kasta utama Liga Inggris (10 pada era Divisi Pertama dan 3 pada era Premier League) dan 13 gelar di Piala FA (Gelar paling banyak). Arsenal memegang rekor untuk periode terpanjang berada di kasta puncak Liga Inggris tanpa pernah terdegradasi sejak musim 1919 dan menjadi tim pada peringkat pertama dalam klasemen Liga Inggris sepanjang abad ke-20.[4] Arsenal menjadi tim kedua di Inggris yang menyelesaikan semusim liga tanpa kalah (musim 2003–04) dan tim pertama yang melakukannya pada era di mana satu musim berlangsung 38 pertandingan."));
            data.add(new Club("https://upload.wikimedia.org/wikipedia/id/thumb/7/7c/Everton_FC_logo.svg/200px-Everton_FC_logo.svg.png", "Everton F.C.", "Everton Football Club /ˈɛvərtən/ adalah sebuah klub sepak bola profesional yang bermarkas di Kota Liverpool, Inggris, dan merupakan klub rival dari klub sekota Liverpool. Didirikan pada tahun 1878 dan menjadi salah satu pendiri dari Liga Sepak Bola (Football League) pada tahun 1888 serta Liga Primer pada tahun 1992.\n" +
                    "\n"+"Saat ini berkompetisi di Liga Utama Inggris, divisi teratas Liga Inggris. Mereka telah berkompetisi di divisi teratas dengan rekor 108 musim, menjadi klub yang paling lama bermain di divisi teratas kompetisi sepak bola Inggris."));
            data.add(new Club("https://upload.wikimedia.org/wikipedia/id/thumb/0/0c/Liverpool_FC.svg/180px-Liverpool_FC.svg.png", "Liverpool F.C.", "Liverpool Football Club /ˈlɪvərpuːl/ (dikenal pula sebagai Liverpool atau The Reds) adalah sebuah klub sepak bola asal Inggris yang berbasis di Kota Liverpool. Saat ini Liverpool adalah peserta Liga Utama Inggris. Liverpool juga merupakan juara bertahan Liga Champions UEFA musim 2018-2019\n" +
                    "\n" + "Liverpool telah memenangkan 6 trofi Liga Champions UEFA (dulu Piala Champions) dan merupakan klub dengan pemegang gelar juara Liga Champions UEFA terbanyak di Inggris dan ketiga di Eropa setelah Real Madrid dan AC Milan[3]. Selain itu Liverpool juga pemegang 3 gelar juara Liga Eropa UEFA[4] dan 4 gelar Piala Super UEFA."));
            data.add(new Club("https://upload.wikimedia.org/wikipedia/id/thumb/e/eb/Manchester_City_FC_badge.svg/200px-Manchester_City_FC_badge.svg.png", "Manchester City F.C.", "Manchester City Football Club (dikenal pula sebagai Man City atau The Citizens) adalah sebuah klub sepak bola profesional dari Inggris yang bermain di Liga Premier Inggris. Klub ini merupakaan klub sekota dengan Manchester United dan bermarkas di Stadion Etihad, Manchester.\n" +
                    "\n" + "Pertandingan pertama dimainkan pada bulan November 1880. Pada saat itu masih bernama St Mark's (West Gorton). Pada tahun 1887 berubah nama menjadi Ardwick A.F.C, dan pada tahun 1894 menjadi Manchester City F.C."));
            data.add(new Club("https://upload.wikimedia.org/wikipedia/id/thumb/7/7a/Manchester_United_FC_crest.svg/220px-Manchester_United_FC_crest.svg.png", "Manchester United F.C.", "Manchester United Football Club adalah sebuah klub sepak bola profesional Inggris yang berbasis di Old Trafford, Manchester Raya, yang bermain di Liga Inggris. Didirikan sebagai Newton Heath LYR Football Club pada tahun 1878, klub ini berganti nama menjadi Manchester United pada 1902 dan pindah ke Old Trafford pada tahun 1910."));
            data.add(new Club("https://upload.wikimedia.org/wikipedia/id/thumb/5/56/Newcastle_United_Logo.svg/200px-Newcastle_United_Logo.svg.png", "Newcastle United F.C.", "Newcastle United Football Club adalah klub sepak bola profesional Inggris yang berbasis di Newcastle upon Tyne, dan bermain di Liga Utama Inggris, kompetisi tingkat teratas dalam sepak bola Inggris. Newcastle United didirikan pada tahun 1892 sebagai hasil penggabungan Newcastle East End dan Newcastle West End, dan bermain di kandangnya saat ini, St James' Park, sejak saat itu. Stadion tersebut dikembangkan menjadi stadion all-seater pada pertengahan 1990-an dan memiliki kapasitas 52.354."));
            data.add(new Club("https://upload.wikimedia.org/wikipedia/id/thumb/8/8c/Norwich_City.svg/150px-Norwich_City.svg.png", "Norwich City F.C.", "Norwich City Football Club adalah sebuah klub sepak bola Inggris yang didirikan pada tahun 1902. Bermarkas di Norwich, Norfolk. Norwich pada musim 2006-07 bermain di Liga Championship Inggris. Klub ini memainkan pertandingan kandangnya di Stadion Carrow Road yang berkapasitas 26.164 penonton. Seragam mereka berwarna kuning-hijau, sehingga mereka dijuluki Canaries (Kenari)."));
            data.add(new Club("https://upload.wikimedia.org/wikipedia/id/thumb/b/b4/Tottenham_Hotspur.svg/140px-Tottenham_Hotspur.svg.png", "Tottenham Hotspur F.C.", "Tottenham Hotspur Football Club /ˈtɒtənəm/,[1][2] adalah klub sepak bola yang berasal dari Tottenham, sebuah daerah yang berada di wilayah utara London. Mereka juga dikenal sebagai Spurs, The Spurs dan Tottenham, sementara penggemar mereka memberi mereka nama the Lilywhites karena seragam tradisional mereka yang berwarna putih."));
            data.add(new Club("https://upload.wikimedia.org/wikipedia/id/thumb/f/fc/Wolverhampton_Wanderers.svg/200px-Wolverhampton_Wanderers.svg.png", "Wolverhampton Wanderers F.C.", "Wolverhampton Wanderers Football Club adalah sebuah klub sepak bola Inggris yang bermarkas di Wolverhampton, Britania Raya yang bermain di Liga Utama Inggris. Klub ini memainkan pertandingan kandangnya di Stadion Molineux yang berkapasitas 32,050 penonton. Seragam mereka berwarna cokelat-hitam. Mereka dijuluki Wolves."));
        }
        return data;
    }
}
